### ISSUE TITLE
Fail to build v0.5.0 in Windows 10: Cannot open include file: 'pthread.h'

### ISSUE THREAD

**Issue by abribanez** [Autodesk/maya-usd#1001]
**Describe the issue**
Hi all!
I'm trying to build maya-usd for Maya 2020 but I keep getting `Cannot open include file: 'pthread.h'` in the logs and I haven't had any luck finding a solution in other tickets/issue-threads. Any help would be greatly appreciated. Cheers!

**Build log**
[build_log.txt](https://github.com/Autodesk/maya-usd/files/5685968/build_log.txt)
[CMakeOutput.log](https://github.com/Autodesk/maya-usd/files/5685969/CMakeOutput.log)
[CMakeError.log](https://github.com/Autodesk/maya-usd/files/5685970/CMakeError.log)

**Specs:**
 - OS: Windows 10
 - Compiler: Visual Studio 2017 
 - Maya 2020.2
 - Maya USD commit: v0.5.0 (62037f3874df7bd8393b4c4684b1d3952911af35) (also tried with v0.4.0)
 - Pixar USD commit: v20.11 (d8a405a1344480f859f025c4f97085143efacb53) (also tried with v20.02)
 - Python 2.7.15 64bit

**Additional context**

Repro for USD build:
- Open x64 Native Tools command prompt for VS 2017
- `git clone https://github.com/PixarAnimationStudios/USD.git`
- `git checkout v20.11`
- `python build_scripts\build_usd.py "C:\USD" --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem"`

Repro for maya-usd build (**errors**):
- Open x64 Native Tools command prompt for VS 2017
- `git clone https://github.com/Autodesk/maya-usd.git`
- `git checkout v0.5.0`
- `python build.py --maya-location "C:\Program Files\Autodesk\Maya2020" --pxrusd-location C:\USD --devkit-location C:\devkitBase C:\workspace -v 3`

I tried using `--generator "Visual Studio 15 2017 Win64"`, or `--generator "Ninja"` (pointing args to ninja.exe), or using the `-DBUILD_STRICT_MODE=OFF`, but it looked like I had the same result in all cases.

Again, I would greatly appreciate any help that you could provide me. Cheers!  :)

**Comment by kxl-adsk** [comment]
Hi @abribanez,

All the instances of this issue in the past were related to the fact that one compiled USD without `--build-args boost,"--with-date_time --with-thread --with-system --with-filesystem"`.  In fact, this is exactly how I compile USD on my windows boxes for Maya 2020.

A few things for you to try:
1. Do a clean build of USD
2. Try building maya-usd with USD binaries from our installer (to confirm that issue is related to how USD is compiled)
3. Wait for our upcoming 0.6.0 binaries that will have USD 20.11

FWIW. I will convert this issue to discussion since for now there is nothing actionable for us.

Cheers,
KxL
