### ISSUE TITLE
Can we write UV metadata to allow easier discovery of uv roles?

### ISSUE THREAD

**Issue by koen-v** [Autodesk/maya-usd#1251]
When we need to interpret the uv sets in a usd outside of maya, the index of the of set is more important then the name. 

I propose this as an extension of  UsdMayaWriteUtil::WriteMap1AsST(). Ideally we would like to write all the uv sets as st, st1, st2 etc. 
 
In order to enable round-tripping with maya, we can store some meta data, just like we do for the skeleton and interpret this on import. For example:

```
 texCoord2f[] primvars:st = [...] (
            customData = {
                dictionary Maya = {
                    int index = 0
                    token name = "map1"
                }
            }
            interpolation = "faceVarying"
        )

int[] primvars:st:indices = [0, 1, 2, 3, 3, 2, 4, 5, 5, 4, 6, 7, 7, 6, 1, 0, 1, 6, 4, 2, 7, 0, 3, 5]

texCoord2f[] primvars:st1 = [...] (
            customData = {
                dictionary Maya = {
                    int index = 1
                    token name = "my_second_uvset"
                }
            }
            interpolation = "faceVarying"
        )

int[] primvars:st1:indices = [0, 1, 2, 3, 3, 2, 4, 5, 5, 4, 6, 7, 7, 6, 1, 0, 1, 6, 4, 2, 7, 0, 3, 5]

texCoord2f[] primvars:st2 = [...] (
            customData = {
                dictionary Maya = {
                    int index = 2
                    token name = "my_third_uv_set"
                }
            }
            interpolation = "faceVarying"
        )

int[] primvars:st2:indices = [0, 1, 2, 3, 3, 2, 4, 5, 5, 4, 6, 7, 7, 6, 1, 0, 1, 6, 4, 2, 7, 0, 3, 5]
```

I have some code to enable this behavior, it's not quite ready for primetime. What would be a good way to allow you guys to look at this to consider it? Shall I create a pull request for this ( I dont know how to do 2 pull requests at the same time as I can only fork the depot once, I can do that after the other one is done) ?

Thanks,
Koen

**Comment by kxl-adsk** [comment]
@koen-v Can you describe a bit more the workflow that you are trying to implement? Why do you need to rely on the index? Is it something specific to your studio pipeline or others will need it as well? BTW. I almost wonder if we should start this as a discussion conversation first and then convert to an issue - something to consider for next time.

The best to show us the code would be a DRAFT pull request. You can create as many as necessary pull requests and draft pull requests from a single repository. In order to achieve this, you will create a `feature` branch per the pull request you are working on. This is one thing that is different from what I saw you did currently, i.e. you opened a pull request from your dev branch. The flow for you to try:
- checkout the dev branch (without any modifications)
- create a new feature branch out of it
- commit changes to this new feature branch
- push the branch to remote
- open PR

**Comment by koen-v** [comment]
Ha thanks very much for those last few steps, that's exactly the part I did not understand.

Sorry about creating an issue, I meant this as a discussion point. We have unnamed uv sets in the game, and in the asset manager you just pick 0,1,2 etc. In the current exporter, we follow the indices we get from Maya when defining the order in our custom format. For USD, I would like a similar workflow. To make an object with multiple uv's look the same when exported as a usd vs what we do now, I need to know a little bit more then just the name to make the connections on the other end, does that make sense?

Over time we could adjust out pipeline to allow users to pick uv sets by name in the asset manager, but we would first like to replace the old format without any tool changes and then start using the newly gained features.

Thanks,
Koen

**Comment by kxl-adsk** [comment]
If I understood it well, what you need is to preserve the original indexing when UV sets were authored in Maya. Exporter currently will export them in the same order as authored, so you should be able to use this order when presenting the list of options in your asset manager?

Another option would be to rename UV sets in Maya prior to export. This will allow you to use whatever naming convention you need, including st, st1, st2, stN-1.
