### ISSUE TITLE
[EMSUSD-599] USD files not registered in the filePath editor

### ISSUE THREAD

**Issue by yolov** [Autodesk/maya-usd#1337]
**Describe the bug**
usd files are not registered in the maya file path editor. This makes maya unaware that there are usd file dependencies to the maya scene and also archiving a maya scene will not pack the usd files.

**Steps to reproduce**
1. load any usd file in maya
2. go to window > general editors > filepath editor // it will be empty
or alternatively
2. save the maya scene
3. go to file > archive and inspect the resulting archive

**Expected behavior**
USD files to show up in the filepath editor and to be packed with maya scene archiving.

**Specs (if applicable):**
 - Windows 10
 - Maya 2022
 - Maya USD 0.9.0

**Comment by swillisart** [comment]
Adding this here as the method in which both _File Path Editor_ and _File>Archive Scene_ use to get files paths is from the command **listAttr -usedAsFilename** 
The mayaUsdProxyShape does not currently yield it's path(s) to it.

**Comment by santosg87** [comment]
@yolov we have made a fix for this issue on #3482. it is worth noting that registering the usd file paths still doesn't solve the archiving issue - but you should be able to see the files on the file path editor with that fix.

the fix is not currently on any of the released versions of mayaUSD, you would need to compile the plugin with a commit that includes #3482 in order to see the fix!

closing this issue for the time being. if this is still a problem feel free to reopen :)

**Comment by yolov** [comment]
Thanks, @santosg87.
