### ISSUE TITLE
[MAYA-112438] StandardSurface shader opacity/transparency not supported in Maya>USD export

### ISSUE THREAD

**Issue by mallochj** [Autodesk/maya-usd#1507]
When exporting a USD from Maya, neither the StandardSurface's transparency or opacity channel is exported. Conversely, Lamberts, Blinns and USD proxy surface all export transparency correctly.

This is a big problem because without transparency/opacity, the StandardSurface is only partially useful for USD exports.

Tested with maya-usd v0.10.0 (and earlier versions), Maya 2022 with Windows x64.

**Comment by JGamache-autodesk** [comment]
There is no perfect solution for this issue.

We currently export non textured transmission values as opacity. So if you set the transmission value to 0.25 on the standard surface node, we export an opacity of 0.75 on the UsdPreviewSurface shader.

This is not actually correct since there is an actual opacity parameter on the standard surface shader, but it is a float3. We could modify the code to export that parameter when non-textured by computing the luminance of the 3 color channels.

I strongly suspect you want to export textured opacity. Is that right?

After a lot of pondering, since you are not the first one to ask this question, I would like to propose this solution:

- We will export the luminance of a non-textured opacity to USD preview surface opacity attribute
- If the opacity is connected to a texture node, and we have a **very strong hint** which channel drives opacity, we will export a UsdPreviewSurface shader node where the opacity is explicitly connected to that channel on the corresponding exported UsdUVTexture node.

We define **very strong hint**" as something that looks like this in Maya:
![image](https://user-images.githubusercontent.com/56274617/122464341-bc7eee80-cf84-11eb-861c-e28a53e2d74f.png)
In that case it is very clear that the red channel of the texture is driving the opacity (and the standard surface shader will render correctly).

This means that on import, we connect the standard surface node to the imported file node using the *very strong hint* method with the channel used on the texture.

Would that work with your workflows?

**Comment by ysiewappl** [comment]
> If the opacity is connected to a texture node, and we have a very strong hint which channel drives opacity, we will export a UsdPreviewSurface shader node where the opacity is explicitly connected to that channel on the corresponding exported UsdUVTexture node.

Would it be possible to infer this to be case even if the end-user doesn't elect to connect all child plugs? The reason I ask is that most likely artists are going to assign a texture directly without going and re-connecting manually, and in most cases the opacity texture should be grayscale anyway, so in practice it should work as expected. Otherwise it might be a little unexpected if an artist connects a texture and the exporter doesn't recognize it's meant to be using it without them going into the node editor and manually connecting as needed.

**Comment by JGamache-autodesk** [comment]
Yes, monochhrome texture definitely falls into the **very strong hint** category, thanks for mentioning it. We can definitely do that.

The **triple connection** hint would be necessary only with something like a single RGB texture with: roughness in R channel, metalness in G channel, and opacity in B channel, for example. I have seen a few of these recently.

**Comment by mallochj** [comment]
JGamache-autodesk, thank you for your proposed solution, this sounds great.

The possibility to channel a bitmap texture into the Opacity slot of the Standard Surface shader would be excellent.

Most artists will be careful about connecting the nodes correctly and will work around the system, so whether it's a greyscale bitmap connected into the RGB slots of the standardSurface opacity, or similar, then it is all workable and very useful!

**Comment by JGamache-autodesk** [comment]
Logged internally as MAYA-112438

**Comment by daviddeacon** [comment]
On a related note, I've been having a similar problem to an artist over on the SideFX forums. When bringing in USD exported from solaris.

https://www.sidefx.com/forum/topic/78050/

The dev's responds and points to a possible a wrong interpretation of the USD data when coming into Maya and unreal. 

> "It could be argued that it's Maya and Unreal that have a bug. If texture file has RBGA planes, it's clear that the A should be taken from the Alpha plane. If the texture file has only RGB panes, what do would you assume Alpha to be? Clearly 1, no? The USD standard for the `UsdUVTexture` shader primitive says the fallback value is (0.0, 0.0, 0.0, 1.0) and that's what the translated primitive specifies. 
> 
> So it all indicates that Maya and Unreal interpret it wrong, using the fallback value only if texture file is not found, but not considering the 'per component' fallback values."

If you're going to be working on this part of the code it might be worth taking a look at too.

David

**Comment by JGamache-autodesk** [comment]
Sorry, this one is a little bit more complex. Maya will very helpfully compute an alpha channel using the luminosity of the RGB channels, so you automatically get the "alpha is luminance" behavior on textures without an alpha channel as soon as you connect the outAlpha attribute.
I could not find any option to deactivate this behavior, which is hardcoded in the shader code, and this is not something I can just go and change without affecting a lot of users that depend on this behavior. This would require escalating to product owner level and try to get agreement on what should be the expected behavior, along with options to opt-out of that behavior if requested.

**Comment by mallochj** [comment]
> Sorry, this one is a little bit more complex. Maya will very helpfully compute an alpha channel using the luminosity of the RGB channels, so you automatically get the "alpha is luminance" behavior on textures without an alpha channel as soon as you connect the outAlpha attribute.
> I could not find any option to deactivate this behavior, which is hardcoded in the shader code, and this is not something I can just go and change without affecting a lot of users that depend on this behavior. This would require escalating to product owner level and try to get agreement on what should be the expected behavior, along with options to opt-out of that behavior if requested.

Hi JGamache
For now, any method to export opacity would be essential. If a file node's outAlpha cannot currently work due to the 'alpha is luminance' behaviour, then a separate opacity texture connected to the RGB would be absolutely fine (from my perspective).
