### ISSUE TITLE
MAYA-114282: User preference to delete USD objects rather than deactivate them on delete

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#1538]
Pixar production uses Maya to construct USD scenes, and part of this process involves frequently make structural edits, including adding, reparenting, and deleting prims. Currently, USD objects will only be deactivated when a user attempts to delete them in the Outliner. For our workflows, we would need a way to tell Maya to actually delete these prims rather than simply deactivating them.

**Comment by wtelford** [comment]
USD supports de-activation which is a non-destructive delete. USD also supports clearing opinions, which is a more traditional destructive deletion. Currently Maya's delete command tries to perform a non-destructive de-activation if certain conditions are met. 

Given several paradigms in place, I am currently partial to leaving Maya's delete action performing a de-activation, but we need to add per-prim clearing functionality as well.

**Comment by swillisart** [comment]
Sind de-activation is the preferred deletion operation it would be good to provide a context menu to "clear" the item completely out of the scene in the outliner. Or provide a preference but I think a context option would suffice.

**Comment by santosg87** [comment]
marking this as closed for now. the fix should be available and working on Maya 2023.

**Comment by Dariusz1989** [comment]
I still cant delete prims/clear. Why is this in closed section ? I've literaly open it in UE5, select prim, hit delete, save, reload in Maya. DO I REALLY HAVE TO GO TO UE TO DELETE STUFF ?!?!!?

**Comment by bwtsme** [comment]
It's not fixed for me either. There is no fix that is "working on Maya 2023". I am using the current version, but there is no way.

**Comment by santosg87** [comment]
@Dariusz1989 @bwtsme would you be able to provide a sample file of what you are seeing? I'm wondering if this could be a misunderstanding on our side of what deleting a prim could mean. it seem to work for me.

if i delete a prim - the info about that prim simply is removed from my file. (i.e. if i hit delete on an xform, the data on that prim and its children are simply erased from the file) note that in order to have that change remain, i need to save the changes to my usd file. 

is this not the case for you? are you running into a different result?
