### ISSUE TITLE
variant selection not being passed to Arnold

### ISSUE THREAD

**Issue by mrpurest** [Autodesk/maya-usd#1681]
**Describe the bug**
Switching between geo variants changes the geo in the viewport, but in the render view you always get the default variant.
This bug has been introduced in release version 0.12.0   (in 0.11.0 it works correctly.)

**Steps to reproduce**
create a usdstage from a usd file that has variants in it.
switch the geo variant,
render.

**Expected behavior**
the geo thats rendered should match the geo in the viewport.

**Specs (if applicable):**
 - centos 7
 - Maya 2022.1
 - Maya USD 0.12.0

**Comment by sebastienblor** [comment]
The problem is a bit different actually, it's just that there's not yet a build of MtoA that is compatible with mayaUSD 0.12.

When that happens, MtoA switches to using its builtin usd procedural node to render the proxy shape, which doesn't share all the data with maya-usd.

Because of that, variants won't be taken into account, neither will edits that you'd do in the proxy shape (e.g. translating one of the geometries). 

There's obviously work that needs to be done in order to make all this clear on the user side, as we've seen a lot of confusion recently about these versioning issues. We're working on it.

Meanwhile, if you need arnold and mayaUSD to work properly together, you should stick to 0.11 which is the last compatible version at the moment.

Cheers

**Comment by mrpurest** [comment]
ok,

makes sense - so I am waiting on an updated Arnold version then.

Thanks for the clarification.
