### ISSUE TITLE
missing: USD_GENSCHEMA

### ISSUE THREAD

**Issue by funghetto** [Autodesk/maya-usd#187]
I'm getting this error after building following the instructions on windows 10:

```
CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find USD (missing: USD_GENSCHEMA) (found version "0.19.5")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindUSD.cmake:85 (find_package_handle_standard_args)
  CMakeLists.txt:44 (find_package)
```
Can somebody help me?

**Comment by BigRoy** [comment]
Missing schemas usually happened due to missing `jinja2` in your Python installation. Make sure you have it available as you compile `USD`.

Also, what branch of `maya-usd` are you trying to compile? Make sure you check [`doc/DEVELOPER.md`](https://github.com/Autodesk/maya-usd/blob/dev/doc/DEVELOPER.md#source-versions) for the branch you are trying to compile to ensure you have the right USD version that is compatible with it. E.g. 0.19.5 will not work with the `dev` branch.

Hope that helps.

**Comment by funghetto** [comment]
Thanks that fixed it.
