### ISSUE TITLE
[MAYA-121365] Chinese version

### ISSUE THREAD

**Issue by DaveLi78** [Autodesk/maya-usd#1933]
The USD support of the Chinese version of Maya software is not friendly, and it is completely impossible to edit and create the USD layer in the outline view.

**Comment by santosd** [comment]
Hello @DaveLi78,
We currently don't have have support for other languages for Maya USD. So I understand that you may not be seeing any Chinese translation. However, when you say that it is completely impossible to edit and create the USD Layer in the Outline view. Can you further explain what is happening? Would it be possible to attach a screen capture or a video of what you are seeing on your end? Even though there is no translation things should be working as expected.

I look forward to hearing back from you.

**Comment by DaveLi78** [comment]
Hello @santosd，
Thank you very much for your attention. When I use the Chinese version, right-clicking on stagesShape in the outline editing view does not show the USD layer editor and create a new Prim, which makes me unable to perform subsequent operations. The appearance of these problems does not exist in the English version of the same platform. I will attach a picture reference, the red area on the left is the Chinese version in question, and the green area on the right is the normal English version. The version tested above is maya2022.3, the running platform is window10 19043 version, the CPU is amd3700x memory 32G graphics card RTX2070s and the window11 version CPU is amd3900x memory 32G graphics card RTX3070.
![Snipaste_2022-01-11_08-51-19](https://user-images.githubusercontent.com/49333212/148864205-7cc6e1cf-2f5b-4d14-a1cc-3d54f3b3f29a.jpg)

**Comment by santosg87** [comment]
Hi @DaveLi78,

we managed to narrow down the issue and a fix should be available in future Maya builds. 
the problem seems to be due to a case sensitive argument that blocks the chinese resource files from loading the necessary USD fles.

for the time being, there is a possible workaround to get things working in chinese, unfortunately it involves modifying things on the Maya installed folder, so you will need admin permissions. the fix is simple:

* locate the "MayaStrings" file on the installed maya folder (should be under "C:\Program Files\Autodesk\Maya2022\resources\l10n\zh_CN"
* with a text Editor, search for line containing "rWorldStrId".
* replace the last argument "World" with "world" (you should have something looking like [(...).s_HentityStrings.rWorldStrId = "world"] afterwards)
* Save that 

hope it helps!

I am marking this as closed for the time being, feel free to re-open the file if this is still a problem

**Comment by DaveLi78** [comment]
Thank you very much for your reply, I used this method to successfully fix the error in the Chinese version, a great discovery.
----- 原始邮件 -----
发件人：George Santos ***@***.***>
收件人：Autodesk/maya-usd ***@***.***>
抄送人：David卫 ***@***.***>,  Mention ***@***.***>
主题：Re: [Autodesk/maya-usd] [MAYA-121365] Chinese version (Issue #1933)
日期：2022年03月16日 00点38分


Hi @DaveLi78,
we managed to narrow down the issue and a fix should be available in future Maya builds.

the problem seems to be due to a case sensitive argument that blocks the chinese resource files from loading the necessary USD fles.
for the time being, there is a possible workaround to get things working in chinese, unfortunately it involves modifying things on the Maya installed folder, so you will need admin permissions. the fix is simple:

locate the "MayaStrings" file on the installed maya folder (should be under "C:\Program Files\Autodesk\Maya2022\resources\l10n\zh_CN"
with a text Editor, search for line containing "rWorldStrId".
replace the last argument "World" with "world" (you should have something looking like [(...).s_HentityStrings.rWorldStrId = "world"] afterwards)
Save that

hope it helps!
I am marking this as closed for the time being, feel free to re-open the file if this is still a problem

&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
