### ISSUE TITLE
[MAYA-128007] Channel Box & Attribute Editor: Customize or provide nice names for attributes

### ISSUE THREAD

**Issue by gracekumagai** [Autodesk/maya-usd#1947]
**Is your feature request related to a problem? Please describe.**
At the moment, the xformOp names displayed in the channel box and attribute editor are long and can be confusing for the user. The prefix "xformOp:" makes it challenging to quickly scan the channel box and find the attribute you are looking for.

**Describe the solution you'd like**
We would like to be able to customize the attribute names that are displayed in the channel box and attribute editor. Ideally, we would like to be able to customize them to look like native Maya to help with the transition to maya-usd.

Native Maya:
![channelbox_maya](https://user-images.githubusercontent.com/12554015/148100484-f6efb893-f0b2-4017-b985-be9299e62abd.png)

maya-usd:
![channelbox_ufe](https://user-images.githubusercontent.com/12554015/148100587-93fd707d-1c24-4382-adc9-b8934974e309.png)

**Describe alternatives you've considered**
It may be helpful to leverage the menus for changing the nice, long or short attribute names in the channel box or attribute editor.
- In the channel box, navigate to Edit -> Channel Names
- In the attribute editor, navigate to Display -> Attribute Names

**Comment by dj-mcg** [comment]
This is internal Pixar Jira MAYA-3184

**Comment by gracekumagai** [comment]
Given #2180 being closed out, I was wondering if this ticket has been revisited? Thanks!

**Comment by womanyoyoyo-adsk** [comment]
Hi @gracekumagai, we haven't revisited this ticket. I'm going to keep this open.

**Comment by seando-adsk** [comment]
@gracekumagai Currently in the AE we do support the "Nice Names" and setting by taking the attribute name and prettifying it with capitals, spacing, etc. No customization is supported. In the Channel box we didn't add any support for the "Channel Names" menu. So the attribute name is always displayed exactly as given by USD.

Here I'm thinking we could use the new "Object Display Name" added in USD v23.02. Supporting this in the AE would be simple. When set to "Nice names" we just query if there is a display name set and use it, otherwise fall-back to our existing "prettify" name.

For the Channel Box this would require a change in both Ufe and Maya. In Ufe we would add new method Ufe::Attribute::getDisplayName() which we can query in the ChannelBox.

Would this proposal work for you? If so I'll get this logged internally have have design validate it.

Sean

**Comment by dj-mcg** [comment]
Hi @seando-adsk - if your proposal includes using the "Object Display Name" in the channel box, this sounds like it would suit our needs... thanks and sorry for the delay in the reply!

**Comment by wallworm** [comment]
Our updated thinking on this is this logic. Please review and share your thoughts.

When either the Attribute Editor or Channel Box are set to display attribute nice names we will follow these rules:

1. If an attribute has the display name explicitly set from USD using the object's display name (metadata), this will be used on the label.
2. For attributes that we already now how to make pretty we will follow the same translation we use in the attribute editor plus a new set of rules to make the name pretty, such as removing xformop.
3. For everything else, we fall back to the attribute as provided.

**Comment by santosg87** [comment]
this issue has been address in MayaUSD 0.27.0. marking this as closed for the time being.
