### ISSUE TITLE
USD Export "mergeTransformAndShape" flag issue with constraints?

### ISSUE THREAD

**Issue by KoljaHuebschmann** [Autodesk/maya-usd#2070]
**Describe the bug**
Currently I ran into the issue with "mayaUSDExport" and the "mergeTransformAndShape" flag.
If an object with an shape has an constraint the "mergeTransformAndShape" flag is ignoring that object.

**Steps to reproduce**
Here a snipet to reproduce that issue:
```
import os
from maya import cmds
cmds.file(new=True, force=True)

# create setup
cube_a = cmds.polyCube(name='cube_a')[0]
cube_b = cmds.polyCube(name='cube_b')[0]
cmds.parentConstraint(cube_a, cube_b, mo=True, name='cube_parentConstraint')

# export usd
example_file_path = os.path.join(os.path.expanduser('~'), 'example_usd_export_has_shape_bug.usd')
cmds.mayaUSDExport(file=example_file_path, mergeTransformAndShape=True)
```

The script writes this usd content (simplified): 
```
def Mesh "cube_a" (
    kind = "component"
)

def Xform "cube_b" (
    kind = "component"
)
{
    def Mesh "cube_bShape" (
    )
    def Xform "cube_parentConstraint"
}
```

**Expected behavior**
With the "mergeTransformAndShape" flag on, i would assume cube_b is the mesh object and it has an xForm for the constraint as children, like this:

```
def Mesh "cube_a" (
    kind = "component"
)

def Mesh "cube_b" (
    kind = "component"
)
{
    def Xform "cube_parentConstraint"
}
```

**Attachments**

**Specs (if applicable):**
 - Windows 10 and CentOS
 - Compiler & version 0.13.0
 - Maya version 2022.3

**Additional context**

As a workaround I used the filterTypes flag, to ignore the constraints:

`cmds.mayaUSDExport(file=example_file_path, mergeTransformAndShape=True, filterTypes=['parentConstraint'])
`

This can cause confusion if you dont notice that in this example scenario: 
You have a "asset bundle" based on usd layering.
model and shading has been done as seperat layers. Then the rigging department overs there "rig" layer and then you might get double shapes or the shading might not apply correct because of this issue.

**Comment by kxl-adsk** [comment]
I was curious about this one and I believe the issue comes from the fact that Maya adds a parent constraint under `cube_b`. Then during translation, we have a code that checks for exportable children and if there are more than 1...the code can't do the merge: https://github.com/Autodesk/maya-usd/blob/d268a25cd7eae42a47da85d32128e7eb01c5d3ed/lib/mayaUsd/fileio/writeJobContext.cpp#L135

The workaround you found is exactly what I would recommend. Changing a default for us is something that is not a simple task (e.g. some may consider it as a regression in the export code). Maybe you could take advantage of [job context](https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/fileio/doc/Managing_export_options_via_JobContext_in_Python.md) and pre-configure the export for everyone the same way?

**Comment by KoljaHuebschmann** [comment]
Thanks  for looking into this and your quick reply!

Finaly I was able to check the code.
So technicaly any "shape transform" would keep the shape node if its not only one child node (with some exception, skipping "non render shapes" aka "intermediateObjects" or maya defaults).
 
This makes it more worse if you excpect "mergeTransformAndShape" will do what it says. 
For example: I parent `cube_a` under `cube_b`. The cube_b keeps it shape while cube_a does not.
This can not be solve with using the "filterTypes" flag, it would requiere an custom export script or a pythonPostCallback.

Another issue I found with this behavior is that an USD Import gets destructive, because the cube_bShape will become the new "maya transform" with an extra mesh shape.

Technicaly it is possible in USD to create a mesh object with another mesh object or transfrom/xfrom as child. If I turn of "shape" display in mayas outliner, this would be the result I would assume in the stage as well with the flag turned on.

So if it is okay, I would like to keep this open as an issue, because I can not imagine that someone might consider a regression.

Thank you for the hint with the job context, this is a nice feature setting up artists custom exports will take advantage with it!

**Comment by kxl-adsk** [comment]
Not sure if you happen to read this note about Gprims in [USD Terms and Concepts](https://graphics.pixar.com/usd/release/glossary.html#usdglossary-gprim):
>  We strongly discourage nesting gprims under other gprims. This is because many key features of USD apply hierarchically, such as [activation](https://graphics.pixar.com/usd/release/glossary.html#usdglossary-active-inactive), [visibility](https://graphics.pixar.com/usd/release/glossary.html#usdglossary-visibility), and [purpose](https://graphics.pixar.com/usd/release/glossary.html#usdglossary-purpose), and it can be frustrating and counter-productive to be unable to apply these operations to individual gprims.

**Comment by KoljaHuebschmann** [comment]
No have not read/known this before and brought the topic into our pipeline meeting.
You are right, this makes it much more complex to implement and in the gprim under gprim case wrong from a USD standpoint. Thanks for the clarification!

Will close the ticket. 

If this topic will come up more often, maybe a "forceMergeTransformAndShape" flag would be a nice feature in addition and a hint in the doc:
https://github.com/Autodesk/maya-usd/blob/dev/lib/mayaUsd/commands/Readme.md

Because still, from a not technical standpoint I would expect a stage hierachy like when I turn off "shape" display in the outliner.

**Comment by sbissonnette** [comment]
I had exactly this issue this week, I wanted to export a Camera but it had a constraint right under it. 
By using `filterTypes=['constraint']` it should ignore any type of constraint.

> As a workaround I used the filterTypes flag, to ignore the constraints:
> `cmds.mayaUSDExport(file=example_file_path, mergeTransformAndShape=True, filterTypes=['parentConstraint']) `

**Comment by bazhutkin** [comment]
I also encountered this problem when exporting. Please provide support for types of the parent class so as not to list all types of constraints. For now, as a solution, before exporting, I remove all the constraints from the selection.
`cmds.select(cmds.ls(sl = True, type = 'constraint'), d = True)`

I also noticed a bug that the constraints are still exported if the main group is selected, it also had to be removed from the selection.
`cmds.select('geo', d = True)`

**Comment by BigRoy** [comment]
I know this issue is closed - but just wanted to state that I too was confused that having a constraint under a transform meant the Shape not getting merged with the Transform.

The issue is easily shown by creating to cubes, parenting one to the other:
```python
from maya import cmds

cube_a = cmds.polyCube(name="a")[0]
cube_b = cmds.polyCube(name="b")[0]
cmds.parentConstraint(cube_a, cube_b)
```

Then selecting just the cube, not the constraint, shows the same issue:
```python
cmds.select([cube_a, cube_b])
cmds.mayaUSDExport(file="E:/test.usda", selection=True)
```
This basically exports one NOT merged.

As stated above, using `filterTypes` flag does resolve it. For example:
```python
cmds.select([cube_a, cube_b])
cmds.mayaUSDExport(file="E:/test.usda", selection=True, filterTypes="constraint")
```

However, as far as I can see this flag is not currently exposed in the UI for non-tech savvy artists.

Then getting back to this:

> We strongly discourage nesting gprims under other gprims. This is because many key features of USD apply hierarchically, such as [activation](https://graphics.pixar.com/usd/release/glossary.html#usdglossary-active-inactive), [visibility](https://graphics.pixar.com/usd/release/glossary.html#usdglossary-visibility), and [purpose](https://graphics.pixar.com/usd/release/glossary.html#usdglossary-purpose), and it can be frustrating and counter-productive to be unable to apply these operations to individual gprims.

I understand the 'recommendation' however, the parent constraint converts to an `Xform` which technically isn't a `GPrim` - which as far as I know isn't necessarily what they refer to here? It might be semantics but like others here I got confused by this.

For now we'll just always be filtering constraints by default.
