### ISSUE TITLE
[0.16.0] USD library mismatch

### ISSUE THREAD

**Issue by quentinBirrer** [Autodesk/maya-usd#2108]
**Describe the bug**
The USD provided with the installer executable have USD library mismatching with USDPixar-21.11, and look to be preventing using an external USD version.
Having our environment pointing to an external USD prevent MayaUsdPlugin to load.
```
loadPlugin mayaUsdPlugin;
// Error: line 1: Unable to dynamically load : path_to_mayausd/MayaUSD2/plugin/adsk/plugin/mayaUsdPlugin.mll
The specified module could not be found.
 // 
// Error: line 1: The specified module could not be found.
 (mayaUsdPlugin) //
```

**Steps to reproduce**
Change the USD path in the mayausd.mod to an external USD-21.11 build.

**Expected behavior**
0.14.0 was fine switching the path to an external USD.
We would like to see the same behavior and having the possibility to use an external USD build, used across our studio.

**Specs (if applicable):**
 - OS & version : Windows 10
 - Compiler & version : -
 - Maya version : Maya 2022.3
 - Maya USD commit SHA : dev at 7c0ffff tag [v0.16.0](https://github.com/Autodesk/maya-usd/releases/tag/v0.16.0)

**Additional context**
Digging into the USD folders provided by the installer, the USD libraries names are mismatching with the USDPixar-21.11 libraries, which are now prefixed with **usd_**.
This would most likely prevent any custom plugins to work with the maya USD libraries.

**Comment by seando-adsk** [comment]
@quentinBirrer As part of USD v21.11 Pixar introduced a new prefix for the libraries ```libusd_``` on Linux/Mac and ```usd_``` on Windows. When we built USD v21.11 we reverted back to the previous behavior by setting ```PXR_LIB_PREFIX="lib"``` on Linux/Mac and ```PXR_LIB_PREFIX=""``` on Windows.

There is also have a corresponding variable in the maya-usd repo ```USD_LIB_PREFIX```

Sean

**Comment by suekieza** [comment]
Hey,
So are you saying we need to rebuild our USD pixar build without the "usd_", will this not cause issues with other DCC's?

Sue

**Comment by seando-adsk** [comment]
If you are not rebuilding MayaUsd and simply want to use our MayaUsd binaries with your own compiled USD, then yes you will need to build USD without the "usd_" prefix. If you are building your own MayaUsd then you can set "USD_LIB_PREFIX" (default is "usd_") to whatever prefix you used to build USD.

BTW, it is probably a better/safer practice to build MayaUsd against any custom USD version to ensure the binaries are ABI compatible.

When this prefix change was made to USD we didn't have time to coordinate it with the other clients of MayaUsd (such as Arnold) for our update to USD v21.11. So we decided to revert back and build that USD version with the previous prefix. This also makes it consistent with all the other USD versions that we support.

We have considered building USD with our own "maya" prefix in order to avoid conflicts. We have seen many problems from users who had conflicting USD binaries.

Sean

**Comment by quentinBirrer** [comment]
When building against our USD, the mtoh plugin fails to load in Maya.
Any lead why that could be ?
```
// Error: file: .../Maya2022/scripts/others/pluginWin.mel line 316: Unable to dynamically load : .../MayaUSD/0.16.0/python-2.7/MayaUSD/lib/maya/mtoh.mll
A dynamic link library (DLL) initialization routine failed.
 // 
// Error: file: .../Maya2022/scripts/others/pluginWin.mel line 316: A dynamic link library (DLL) initialization routine failed.
```
The previous build against USD-21.08 and MayaUSD 0.14.0 was working fine for us.

**Comment by seando-adsk** [comment]
In USD v21.11 we added MaterialX, so its possible this is somehow related. Maybe hydra has visible dependency on MaterialX? Or if you are mixing MayaUSD compiled against USD+MaterialX with USD compiled without it doesn't work?

On Windows there is an excellent tool called "Dependency Walker" or the newer rewrite called "Dependencies" that is very helpful in debugging these kinds of problems.

Sean

**Comment by santosg87** [comment]
@quentinBirrer is this still an issue for you guys?

**Comment by ansuter** [comment]
> If you are not rebuilding MayaUsd and simply want to use our MayaUsd binaries with your own compiled USD, then yes you will need to build USD without the "usd_" prefix. If you are building your own MayaUsd then you can set "USD_LIB_PREFIX" (default is "usd_") to whatever prefix you used to build USD.
> 
> BTW, it is probably a better/safer practice to build MayaUsd against any custom USD version to ensure the binaries are ABI compatible.
> 
> When this prefix change was made to USD we didn't have time to coordinate it with the other clients of MayaUsd (such as Arnold) for our update to USD v21.11. So we decided to revert back and build that USD version with the previous prefix. This also makes it consistent with all the other USD versions that we support.
> 
> We have considered building USD with our own "maya" prefix in order to avoid conflicts. We have seen many problems from users who had conflicting USD binaries.
> 
> Sean

I have the scenario with my own custom USD build (21.11), and my own MayaUSD build (0.18). Will I still be able to properly use Arnold 5.1.3.1 (mtoa) and BiFrost 2.4? I chose to use USD's 'usd_' prefix (since we have many, many other repos dependent on USD outside of Maya as well).

**Comment by seando-adsk** [comment]
Building your own MayaUsd with the USD you built with prefix is good. That means MayaUsd will for sure work. Whether or not mtoa or Bifrost will work I'm not sure. They both use the USD provided by MayaUsd. Since the filenames are different (prefix vs no prefix) I don't think they will correctly find USD. However Bifrost also ships with a minimal USD in the case where it is run standalone (without any MayaUsd). So Bifrost may be able to still find USD libraries. Sorry but I don't know whether mtoa will work.

Sean

**Comment by suekieza** [comment]
> @quentinBirrer is this still an issue for you guys?

Yes we are still having this issue. are you guys going to insure that you follow how pixar builds in the future?

**Comment by seando-adsk** [comment]
Yes going forwards we will build new USD versions (v22.08+) with the standard prefix from Pixar. But this will only affect the Maya beta builds. Maya 2020/2022/2023 are all using the previously built USD v21.11 (which has no prefix).

Sean

**Comment by santosd** [comment]
@suekieza and @quentinBirrer let us know if there are any further questions or if we can go ahead and close this issue out. Thank you.

**Comment by santosg87** [comment]
closing this one for now, based on the last comments, and based on the planned development.
