### ISSUE TITLE
[MAYA-122477] Textures disappear when manipulating a prim when Async Texture Loading is enabled.

### ISSUE THREAD

**Issue by santosd** [Autodesk/maya-usd#2139]
**Describe the bug**
If I have Async Texture Loading enabled and I create a stage from the ALab scene. After all of the prims and textures are loaded if I rotate the decor_helmet_head01_0001 prim the texture will disappear. It only happens on the first move, unless you undo the first move and move the object again.

**Steps to reproduce**
1. Make sure that Asyn Texture Loading is enabled:
`import maya.cmds as cmds
cmds.optionVar(iv=("mayaUsd_DisableAsyncTextureLoading", 0))`
2. Create a stage from the USD_Alab file.
3. Once prims and textures have loaded, select the decor_helmet_head01_0001 prim.
4. Rotate, scale, or translate it and notice that while the prim is being manipulated, the texture will disappear.

**Expected behavior**
After textures have loaded and transformation of the prims would show the texture.

**Attachments**

https://user-images.githubusercontent.com/29235905/155382653-27dd93d3-df7e-4db6-af6a-db6d16dbad0c.mp4

**Comment by williamkrick** [comment]
https://github.com/Autodesk/maya-usd/pull/1980 is the change that introduces async material loading.

**Comment by santosd** [comment]
Hi @williamkrick I retested this issue using the latest changes and this issue is still happening. Should we reassign this issue to try to get it fixed or set this in the backlog for the time being?

**Comment by williamkrick** [comment]
Yes lets log something internally and see if we can get it scheduled.

**Comment by santosd** [comment]
Logged it internally.

**Comment by csyshing** [comment]
Hi @williamkrick @santosg87 , I found that when manipulating a **prim**, USD imaging [removes all material **sprim**s](https://github.com/PixarAnimationStudios/USD/blob/857ffda41f4f1553fe1019ac7c7b4f08c233a7bb/pxr/usdImaging/usdImaging/delegate.cpp#L1018) since they are dependencies of the **prim**, and then [recreate these material **sprim**s](https://github.com/PixarAnimationStudios/USD/blob/857ffda41f4f1553fe1019ac7c7b4f08c233a7bb/pxr/usdImaging/usdImaging/delegate.cpp#L1048) again, this all happen within [`UsdImagingDelegate::ApplyPendingUpdates()`](https://github.com/PixarAnimationStudios/USD/blob/857ffda41f4f1553fe1019ac7c7b4f08c233a7bb/pxr/usdImaging/usdImaging/delegate.cpp#L955):
```C++
void
UsdImagingDelegate::ApplyPendingUpdates()
{
    ....
    indexProxy._ProcessRemovals();  //<-- Removes sprims
    ....
    indexProxy._UniqueifyPathsToRepopulate();
    _Populate(&indexProxy);         //<-- Recreates sprims
    _ExecuteWorkForVariabilityUpdate(&worker);
}
```

When user is holding the mouse button and manipulating, the texture first gets released, but the texture loading happens on idle which is **after** user releasing the mouse button, this is why the texture appears.

I think there might be two options:
1. Stores texture info globally in [`static HdVP2GlobalTextureMap _globalTextureMap`](https://github.com/Autodesk/maya-usd/blob/3885eb01362ef751967e9ca200a304566f8ff723/lib/mayaUsd/render/vp2RenderDelegate/material.h#L164), so that when material itself is destroyed, the texture does not get released along;
2. OR: similar as loading texture asynchronously, we release the texture asynchronously (on idle) as well. If the material has been requested to reload during `UsdImagingDelegate::ApplyPendingUpdates()`, we can just reuse the texture info from cache.

I have submitted a PR for **option 2** for discussion: https://github.com/Autodesk/maya-usd/pull/2228

Let me know what do you think, thanks!

**Comment by santosd** [comment]
Since we have added the feature to load texture with the texture mode option in the viewport we have decided that we will not be focusing on this for the time being so closing this one out.
