### ISSUE TITLE
Make the build instructions more clear on which version of USD to get

### ISSUE THREAD

**Issue by TechArtistG** [Autodesk/maya-usd#220]
The instructions here:
https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md

Are vague as to exactly what to get.

"it is important the recommended Pixar USD and Animal Logic commitID or tag from the table below are used"

Should be more like:
"You MUST get the specific version of USD that matches the current Maya-USD version..."

There's also no mention of which branch of Maya-USD to get,

**Comment by kxl-adsk** [comment]
When using Pixar `dev` branch, then yes, you must use a specific commit ID (otherwise we can't guarantee things will compile given the nature of changes happening in dev branch).
When using Pixar `master` branch, then we currently support 19.07, 19.11, 20.02 releases. 

Something we have to improve in the doc. Thank you for reporting.

**Comment by HamedSabri-adsk** [comment]
@TechArtistG 
I have update the build doc to make it more clear what version of USD to use.
https://github.com/Autodesk/maya-usd/pull/346
Does this help?
