### ISSUE TITLE
[MAYA-122706] Testing MaterialX in Maya 2023

### ISSUE THREAD

**Issue by santosd** [Autodesk/maya-usd#2267]
### Discussed in https://github.com/Autodesk/maya-usd/discussions/2244

<div type='discussions-op-text'>

<sup>Originally posted by **daviddeacon** April  4, 2022</sup>

I've just been testing materialX in 2023, any USD files that I import into the stage that have mtlx shaders they are completely invisible in the Maya viewport. Wireframe is visible when they are selected.

The mtlx shaders seem to be valid as they work fine in Houdini's solaris. 

I'm on macOS 12.2.

Is this expected behaviour currently?

Thanks,
David</div>

**Comment by santosd** [comment]
We were able to reproduce this issue and have logged it internally.

**Comment by santosg87** [comment]
@santosg87 assigning this to test on a Mac Environment

**Comment by daviddeacon** [comment]
I spotted this was meant to be fixed in 0.18.0 release based on the logs, but I've just been testing it Maya 2023 and the just released 0.18.0 build and it's still showing MaterialX materials as transparent ☹️

https://www.dropbox.com/s/rdfywpwcv7xiehl/Screenshot%202022-04-05%20at%2020.43.22.png?dl=0

https://www.dropbox.com/s/b51b3qyp4py3amj/torus_maya2023.usda?dl=0

macOS 12.2 - MacBook Pro M1 Max

**Comment by santosg87** [comment]
hi @daviddeacon I have been testing this on our side, and it seems to work for me as expected. 
<img width="1921" alt="Screen Shot 2022-05-27 at 5 14 25 PM" src="https://user-images.githubusercontent.com/3026529/170790396-c80c8fe0-529c-4543-9768-a55daf35ef8c.png">


we are investigating this to try and reproduce the issue on our side.

**Comment by santosg87** [comment]
@daviddeacon just a small update. 

it seems this is related to the arm architecture chips. we were able to reproduce this internally as well now and we are investigating. :)
