### ISSUE TITLE
Marking Menu for UFE items

### ISSUE THREAD

**Issue by dj-mcg** [Autodesk/maya-usd#2370]
Previously, our users used a workflow that involved a custom marking menu for our point instancer shape. Specifically, we'd be using it to allow users to switch between "instances" and "point instancer" pick modes. With that now in UFE, it would be nice if we could provide a marking menu for UFE selections.

I'm not sure if https://github.com/Autodesk/maya-usd/issues/1773 covers this or not as I haven't been able to test Maya 2023, but from the reading, it sounds like it's a context menu (RMB click), not the marking menu (RMB hold).

One possible solution could be in buildObjectMenuItemsNow, adding:
ls ... -selection -ufeObjects;

and if that did return something, it would call into ufeMenuProc. From there, a similar dispatch to calling $ufeItemType + "UfeMenuProc like is done for dagMenuProc would work, as we'd be able to provide a PointInstancerUfeMenuProc to do what we need.

This is internal Pixar Jira MAYA-3329

**Comment by seando-adsk** [comment]
The discussion in #1773 and the subsequent change in PR #2305 allows you to add your own menu items to the marking menu (via a User callback function) for **non**-Maya Ufe items. This only works in Maya 2023 and later.

In order to add menu items to the marking menu of a Maya item you use one of the existing callbacks (addRMBBakingMenuItems) like we are doing here: https://github.com/Autodesk/maya-usd/blob/dev/plugin/adsk/scripts/mayaUsdMenu.mel#L715
The benefit of this is that it is currently support in older Maya versions.

Sean

**Comment by santosg87** [comment]
@dj-mcg were you able to create UFE marking Menus with the information above? 

is it ok to close this issue for now?

**Comment by dj-mcg** [comment]
We'll need to test it outside our normal development environment since we
don't yet have a vfx2022 dependency set to build our tree against. I'll let
you know what we find, but it may be ok to close this issue out and we can
just file any bugs are missing features as separate issues, if you prefer
