### ISSUE TITLE
[MAYA-103621] Attribute Editor Error with BasisCurves ( ufe_ae enum.py )

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#258]
**Describe the bug**
In the latest maya beta with PR#228, when selecting BasisCurves that are either the original prim definition or referenced prims.

**Steps to reproduce**
1. load maya beta
2. import the attached basisCurves.usdc
3. select any of the prims labeled - myFurryThing, references_1,2 or 3
4. notice the error : "Python\lib\site-packages\maya\internal\common\ufe_ae\enum.py line 33: Item not found"

More details :

Assertion failed: "false"
	File: D:\Repos\maya-usd\lib\ufe\UsdAttribute.cpp
	Line: 99
	Function: `anonymous-namespace'::getUsdAttributeValueAsString
	Description: Could not convert the attribute to a string

5. now select, any of the instanced prims - instanced_1,2 or 3 and there is no error

**Expected behavior**
We expect no error.

**Attachments**
USD File
[basisCurves.zip](https://github.com/Autodesk/maya-usd/files/4168352/basisCurves.zip)

![MayaBetaAttributeEditorError_basisCurve_Selection](https://user-images.githubusercontent.com/2152250/73991387-029c5a80-491a-11ea-8216-d37f5dbbcc6a.png)

**Specs (if applicable):**
 - OS & version [Windows 10]
 - Compiler & version [VS2017]
 - Maya version [Maya Beta and 2020.0 tested]
 - Maya USD commit SHA [dev at a29704f with PR#228 merged in]
 - Pixar USD commit SHA [master v20.02 compiled against rman23]

**Additional context**

**Comment by cfmoore007** [comment]
For what it's worth, it also occurs with Pixar's - PointInstancedMedCity example, when selecting one of the prims.  Most likely, that may be a separate issue, but the error is the same.

**Comment by santosg87** [comment]
we have this logged internally as MAYA-103621.

**Comment by seando-adsk** [comment]
MAYA-103621 deals with the first error (enum.py). We have logged a separate issue (MAYA-103421) logged for the getUsdAttributeValueAsString error. These are two different problems.

**Comment by seando-adsk** [comment]
This has been fixed in Maya and will be available in the next beta.

The problem here is the usd file contains a **BasisCurves** prim type /myFurryThing/curve_0. That prim has an attribute basis with token type with a set of allowed tokens. But this attribute has a value that is **not** in the set of allowed tokens. In this case the value is "" (empty string) so it appears as if the attribute has no value, but it does. You can view this by using **usdcat** to output the contents of the file. You'll see this:
```        uniform token basis = ""```

In Maya, we translate the USD token type to Maya's optionMenu (with all the allowed tokens). But in Maya an optionMenu **must** have one of the items selected. Since the value from the Get() is not one of the values set in the optionMenu we get this error.

What we have is when the current value is not one of the allowed tokens we add it to the optionMenu (as first item). Note: this extra value is not remembered, so if you change the value to one of the allowed tokens and then change selection (AE contents are changed) when you return to that prim that initial (in this case empty) value will be lost.

**Comment by cfmoore007** [comment]
Confirmed fixed in the new beta.
Thanks!
