### ISSUE TITLE
AE : UFE Prim Path Missing

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#267]
**Describe the bug**
Now that UFE prims are shown in the Attribute Editor in the latest Maya Beta, there are a few discrepencies we will split up in different issues.

For this particular issue, the prim or selected object name does not show in the editor.    ( I'm guessing b/c there's no up/downstream connections possibly?) 

**Steps to reproduce**
1. open latest maya beta
2. load usd through proxyShape
3. select prim
4. notice nothing is shown in the node field

**Expected behavior**
Selected prim name is displayed in the Attribute Editor

**Attachments**
**3_Spheres** : 
[3_Spheres_Example.tar.gz](https://github.com/Autodesk/maya-usd/files/4181921/3_Spheres_Example.tar.gz)

**USD Prim**
![UFE_USDPrimPathMissing_in_AE](https://user-images.githubusercontent.com/2152250/74168602-ff45ef00-4bf7-11ea-902d-8addecace3b0.png)
**Dag Object**
![DagPath_in_AE](https://user-images.githubusercontent.com/2152250/74168667-108efb80-4bf8-11ea-85f1-b51be4469016.png)

**Specs (if applicable):**
- OS & version [Windows 10]
- Compiler & version [VS2017]
- Maya version [Maya Beta and 2020.0 tested]
- Maya USD commit SHA [dev at a29704f with PR#228 merged in]
- Pixar USD commit SHA [master v20.02 compiled against rman23]

**Additional context**

**Comment by ppt-adsk** [comment]
Hi Christopher,

This is a known issue, it's really only because development on the feature is incomplete.  The name field at the top of the tab is not just a plain text field, it's a nameField:

https://help.autodesk.com/cloudhelp/2020/ENU/Maya-Tech-Docs/Commands/nameField.html

nameField is renaming-aware: it will generate an undoable rename command on edit, and will update the field on a rename done by another means.  nameField currently wants a Maya node, and of course for USD we don't have one, so nameField needs to be made UFE-aware.  Logged internally as MAYA-101339.

**Comment by cfmoore007** [comment]
Ah, I knew there was more going on behind the scenes.

Thank you for the explanation ( and quick response! ).

**Comment by santosg87** [comment]
As @ppt-adsk pointed out, there is some more work needed here. :)

**Comment by mdelasa** [comment]
We logged this internally as MAYA-101339.

**Comment by seando-adsk** [comment]
This has been fixed and will be available in the next Maya beta.

**Comment by santosg87** [comment]
hi @cfmoore007 this should be fixed now on the latest PR, would yo be able to validate and close this? :)

thank you!

**Comment by cfmoore007** [comment]
Sorry, I thought I already responded to this.

This is now fixed and matches what the AE returns for DAG objects.

<img width="277" alt="PR115_PrimPath" src="https://user-images.githubusercontent.com/2152250/83446370-8bd12300-a41c-11ea-8f78-0451b7ab2c65.png">


Thanks!
