### ISSUE TITLE
[MAYA-125116] MayaUSDExportCommand on a network folder

### ISSUE THREAD

**Issue by kimuss** [Autodesk/maya-usd#2745]
**Describe the bug**
When I try to save a new USD file or save modified USD file on a network path (SMB share folder), give this error: "// Error: Insufficient permissions to write to destination directory "

**Steps to reproduce**
1. Go to 'Create'
2. Click on 'Universal Scene Description-->stage with new layer'
3. Open 'USD Layer Editor'
4. Click on 'Save'
5. Select a SMB share folder (network or mapping path)
6. See error '..Insufficient permissions..'

Tried to save different format, also .usda give the same error.
it seems to have ad old issue:
https://forums.autodesk.com/t5/maya-modeling/insufficient-permissions-to-write-usd-file/td-p/10515409

**Specs (if applicable):**
 - OS & version  Windows 11 22H2
 - Maya version Maya 2023
 - Maya USD Plugin 0.20

**Comment by santosd** [comment]
Hi @kimuss , This has been logged internally and is being tracked. We have triaged the issue and are hoping to put focus on a fix for this soon.

**Comment by kimuss** [comment]
@santosd thank you, I hope you can fix it as soon as possible, at the moment we have only 2 solutions: use a different protocol (NFS), or change destination folder permission to 777.. but both solutions are not feasible.

**Comment by santosg87** [comment]
just posting an update on this issue:

our investigation brought us to the USD core code - more precisely the issue seems to be here:
https://github.com/PixarAnimationStudios/USD/blob/be1a80f8cb91133ac75e1fc2a2e1832cd10d91c8/pxr/base/tf/atomicRenameUtil.cpp#L136

As we mostly are building with vanilla pixar USD code, this is not something we can do much to fix. as mentioned above, the general solution offered is to use NFS.

marking this as a won't fix for the time being. we might re-visit this issue in the future, but there are no plans on working directly on this as of now.

**Comment by kimuss** [comment]
Hi there, Pixar seems to finally closed that ticket, when can we have it on maya plugin?
thank you

**Comment by luxacc** [comment]
Hello,
I've been experiencing the same issue. Will a fix be implemented in Maya? I noticed that this was marked as closed, and a fix was supposedly applied in:

https://github.com/PixarAnimationStudios/OpenUSD/issues/849

**Comment by Amorano** [comment]
Pinging this as a "when is this getting incorporated" question.

**Comment by Ja1zinhuu** [comment]
Are you guys gonna fix this any time soon or not really?

**Comment by ghost** [comment]
We have tested Maya USD version 0.32.0 with Maya 2026, and it has resolved the issue. This is because Maya USD 0.32.0 uses OpenUSD version 24.11, which is newer than OpenUSD 24.03—the version where the fix was originally implemented.
