### ISSUE TITLE
BlendShapes exported to USD should match name from Maya blendShape node

### ISSUE THREAD

**Issue by gelshoffNV** [Autodesk/maya-usd#3156]
To better facilitate roundtripping from maya to usd back to maya, preserving the naming of the blendShape is important. If blendShape targets still exist in Maya, as history, the exported BlendShapes are named by the target shapes ie: Target1Shape or Target2Shape, as opposed to the preferred naming defined in the blendShape node ie: Target1 or Target2. 

**Steps to reproduce**
1. Create mesh named test
2. Duplicate mesh, name it Target1, and manipulate some vertices
3. Create blendshape from Target1 to test
4. Notice the blendShape on mesh has a single control named Target1
5. Create a joint and skin mesh to it
6. Group the joint and mesh (this is required to create a USDSkel for the blendshapes to actually export)
7. Export using skel auto and blendShapes as usda
8. Open the usda, look at the BlendShape prim name, it should be Target1, but it's Target1Shape

**Comment by santosg87** [comment]
Hi @gelshoffNV thank you for the report. I can also reproduce the case on my side. Although, given that Maya needs the Shape nodes in order to modify the blendShape, I am unsure if this is something done by design or a bug. on either case, I have logged this internall\y and will bring it up to the team for discussion. :)

this is logged internally as EMSUSD-102

**Comment by barbalt** [comment]
Solved by #3703
