### ISSUE TITLE
[MAYA-123076] Maya UFE : Display Layer Support

### ISSUE THREAD

**Issue by cfmoore007** [Autodesk/maya-usd#319]
**Is your feature request related to a problem? Please describe.**
Artists would like to be able to select USD Prims (and maybe some DAG objects as well) and put them into Maya's Display Layers.

They use these to break down larger sets/environments for both visual clarity and view port performance.

Specific Use Case :

1. Artist references in shot.usda
2. Variant switches from USD Char -> Maya Rig
3. Artist wants to break up sections of the set ( for various reasons, foreground/background, etc. )
4. Artist wants to add these elements ( USD Prims & Dag objects ) into display layers

**Describe the solution you'd like**
It behaves like existing display layer workflows and feels native to Maya.

**Describe alternatives you've considered**
Custom USD Prim set / grouping management tools in our custom USD Outliner.  Don't really want to go there unless we have to.

**Additional context**
N/A.

**Comment by gracekumagai** [comment]
Here are a few more use cases:
- Managing a very heavy set by splitting it up into different layers
- Selecting groups of similar objects and performing bulk operations (ex: Adding several objects to a layer, right-clicking on the layer and choosing "Select Objects", frame the selected objects in the Outliner, right-click in the Outliner, and Load all the selected objects (#1540)). Moving forward with UFE, it would be nice to be able to toggle the load state directly in the Display Layer editor
- Toggling visibility of objects in the layer using the 1st column
- Referencing the objects in the layer using the 3rd column (ex: Creating a new layer, adding the terrain, and setting it as unpickable so that the artist can swipe select their dressing in the viewport (and not select the terrain))
- Templating the objects in the layer using the 3rd column
- Using layer management functions: delete layer, empty layer, delete selected layers, delete unused layers, etc. 

We would also want to add both USD prims & Dag objects to the layers. Our users would also love for the editor to feel native to Maya.

Thanks!

**Comment by womanyoyoyo-adsk** [comment]
Hi @gracekumagai and @cfmoore00,

Can you please provide a use case for a Display Layer to have both DAG objects and prims? I want to make sure we cover all the uses cases properly while QA'ing. Thanks!

**Comment by gracekumagai** [comment]
Hi @womanyoyoyo-adsk, for USD set dressing, here are a couple examples:
1. An artist might want to use the push/pull workflows to pop out the roof from a piece of USD architecture to get a better view of their dressing within an interior set. It would be helpful to be able to add the (now) native Maya ceiling and any ceiling fixture USD props (ceiling light, fan, sprinkler, etc) to the same layer to toggle visibility. 

2. An artist might want to bring in an approximation of the ground plane or characters from a particular shot (which atm would be brought in as tmp DAG object) for shot-based dressing. It would be helpful to add both their shot based dressing (USD props) and the tmp shot-based objects to a layer to toggle visibility.

Please let me know if you require more examples or details! Thanks!

**Comment by santosg87** [comment]
Maya 2023.2 has new support added for display Layers.

we are working on improving display Layers support and enabling even more workflows in the future, but the basic workflows of adding/removing objects and setting visibility on/off is now available.

note that this feature work requires Maya specific changes, though, which means this is not available on Maya 2023.1 or older builds.

**Comment by gracekumagai** [comment]
Thank you!! We are still getting 2023.2 up and running internally. We will create separate tickets if we run into any issues as we are testing. Thanks again!!
