### ISSUE TITLE
Add support for xgen

### ISSUE THREAD

**Issue by GilbertHuang84** [Autodesk/maya-usd#322]
Xgen is an industry level tool, which can help artist to generate hair with a nice look in few steps. It is well known by the industry, and easy to learn. Currently the xgen just support alembic, which is an industry format for DCCs. That is a pity, it can not support such a fantasy format like USD.

If we can have xgen supporting USD, it would be very nice.

**Comment by wtelford** [comment]
@GilbertHuang84 Maya USD is now compiled with Alembic support which should allow you to bring in an alembic cache via USD. Please comment and re-open the issue if this does not meet your immediate needs.

**Comment by GilbertHuang84** [comment]
OK, thanks for reply. Even it does not help, it is ok, we already find another way to solve it.

**Comment by Sudarshanhavale** [comment]
> Even it does not help, it is ok, we already find another way to sol

Hey @GilbertHuang84,

I am exploring the xgen to USD round trip workflows, Could you please share your workaround to do so? 

I haven't tried the alembic approach yet, but currently, I am dumping all the xgen descriptions into USD using arnold-usd export options which works fine. But In order to make it renderer independent, It would be great to have xgen prims supported inside Maya-usd in the future. :)
