### ISSUE TITLE
Selection of large items imposes high redraw cost

### ISSUE THREAD

**Issue by tryptik** [Autodesk/maya-usd#332]
**The Problem**
Selecting a prim with a high number of children (like a city block) introduces lag while Maya draws the green wireframe for the to indicate the selection highlighting.

**Possible Solutions**
There are a couple of alternatives that come to mind:
- Draw the shapes in a manner similar to USDView. I'm not sure this would save time, but it may faster than layering on the wireframes or could maybe take advantage of a pixel buffer to create an overlay.
- Draw part or all of the bounding box to indicate selection, similar to 3DS Max.
![temp_select (2)](https://user-images.githubusercontent.com/14945011/76016067-07304080-5ed1-11ea-82c1-eb46769469d0.png)

**Comment by santosg87** [comment]
Hi @tryptik, thanks for logging this. 
question - how are you selecting the root prim on that case? through the viewport, or the outliner? I have seen a similar behavior when selecting thigns on the viewport.

**Comment by wtelford** [comment]
@santosg87 can you repro this?

**Comment by santosd** [comment]
Hi @tryptik, since this issue was originally created we have implemented some performance enhancements. I tested similar workflows on my end and I am not seeing a significant delay when selecting a prim with many children for selection highlighting to catch up. Wondering if you could test this again and see if the issue is still present for you.

**Comment by wtelford** [comment]
We believe several performance enhancements have addressed this issue. @tryptik, please feel free to reopen with more information if you are still experiencing the problem with the 0.10.0 or greater.
