### ISSUE TITLE
[EMSUSD-1056] Crash on loading Lumberyard Bistro

### ISSUE THREAD

**Issue by johnhable** [Autodesk/maya-usd#3622]
**Describe the bug**
Felix Herbst kindly made a version of the lumberyard bistro. But when loading any of the meshes as a stage, Maya crashes.

**Steps to reproduce**
1. Download the file BistroInterior.usdz from here:
https://drive.google.com/drive/folders/1fsHeMze6MXu05DbKSCglNWmWK_6dGFci
2. Make a new scene in maya
3. From USD Layer Editor: Create->Stage from File
4. Select BistroInterior.usdz and click "Create"
At that point, Maya crashes.

**Expected behavior**
Expected behavior would be for maya to load the scene as a stage.

**Attachments**
If applicable, add screenshots, sample files, etc to help explain your problem.

**Specs (if applicable):**
 - Windows 10
 - Maya version: 2024.2
 - I'm using the released version, so compiler/github tags are not applicable.

**Additional context**

**Comment by santosd** [comment]
Took a look at this on my end and I am seeing the same thing. I will log this issue internally and continue to test a few things to see if I can find a way to get it to load.

**Comment by johnhable** [comment]
Np. Good luck with the debugging.

**Comment by santosd** [comment]
Hi @johnhable, I logged the issue internally and the fix for it should be coming in our next release of the Maya USD plug-in. If you are able to build the plug-in you could test this and make sure that this is working for you. Otherwise, when the next version is released feel free to test this out and let us know if you encounter any issues. I will go ahead and close this out for the time being.
