### ISSUE TITLE
[MAYA-104979] maya's file command for USD Export always writes .usd extension, even if .usda is passed

### ISSUE THREAD

**Issue by agelosc** [Autodesk/maya-usd#373]
The USD Export through maya's file command writes a .usd file even if a .usda filename is passed in maya's file command argument. The resulting file is named as filename.usda.usd. 

This is an example command that I've used to export:
`cmds.file("<path>/filename.usda", type="USD Export",options="defaultMeshScheme=catmullClark;mergeTransformAndShape=1;exportVisibility=1;exportColorSets=1;exportUVs=1;stripNamespaces=1;frameStride=1;frameSample=0;animation=0;startTime=1;parentScope=;eulerFilter=0;endTime=1;exportInstances=1", preserveReferences=False, force=True)`

 - Windows 10
 - Maya 2020
 - Release [0.1.0] - 2020-03-15

**Comment by santosg87** [comment]
thanks for logging this!

I was able to reproduce this on our side as well. 
interestingly enough, the cmd is the exact same used when exporting through the UI - that however provides the proper result.

we will investigate this further.
than you!

**Comment by santosg87** [comment]
marking it unassigned as we investigate things further :)

**Comment by fowlertADSK** [comment]
I took a quick look at this is also a problem with the Pixar plugin.  It must be a problem because we have file translators that can handle multiple file extensions where typically you just have one.  E.g. Maya has separate Maya ASCII and Maya Binary translators, which is why .ma and .mb show up as separate choices in the dropdown menu of the file dialog, where we have put .usd/.usda/.usdc/.usdz all under the one “USD Export” translator and the user has to type the complete name to get the one they want.

I don’t currently know why it works properly when you call it through the UI but gets it wrong when calling the file command directly, but I’m assuming that nobody has complained about this with the Pixar plugin because pretty much anyone that wants to script this behavior would use the commands that are specific to USD Export/Import and not the Maya file command + its options string.  

We’ll have our commands up soon, at which point this will become a lot less important, but I’ll still try to understand how easy this would be to fix.  The fix might be on the Maya side and not just the plugin though.

**Comment by fowlertADSK** [comment]
@agelosc I spent some time figuring out why going through the file dialog does one thing but calling the command directly does something else and now understand what’s going on.  When you execute the export through the file dialog we do not immediately call the “file” command, we call the projectViewer MEL script first which eventually does a bunch of stuff before actually calling “file”.  One of the things it does is set the -defaultExtensions state on the file command to false.  It queries it before changing it, turns it off, calls the “file” command to export, and then sets it back to the state it was in before.  Changing that global option is why it works properly and is what users would have to do in order to get it to work properly if using the “file” command.

Code would look like this:
{
    // Query and save the current state of defaultExtensions
    int $de = `file -q -defaultExtensions`;
    
    // Turn off defaultExtensions for this export    
    file -defaultExtensions 0;    

    // An example file export call    
    file -force -options ";exportUVs=1;exportColorSets=1;defaultMeshScheme=catmullClark;animation=0;eulerFilter=0;startTime=1;endTime=1;frameStride=1;frameSample=0.0;parentScope=;exportInstances=1;exportVisibility=1;mergeTransformAndShape=1;stripNamespaces=0" -typ "USD Export" -pr -es "path/to/test/file/test_export_extension.usda";
    
    // Put back defaultExtensions to whatever it was before the export
    file -defaultExtensions $de;
}

As annoying as this looks, I think this global state flag in Maya is not going to change any time soon so this issue is probably going to be closed.  The actual import/export commands are coming soon now, and once they are in I don’t think many people would use the “file” command unless they are just trying to copy/paste something from the script editor.

**Comment by agelosc** [comment]
Thank you for having a look at this. This looks like a hard issue to catch. Your workaround is good enough for me. Please go ahead and close this issue if you think it should be closed. 

Thanks again.
