### ISSUE TITLE
[MAYA-105968] Nvidia attic stage - super slow to load

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#460]
**Describe the bug**
I takes over 30 seconds to load simple nvidia attic usd stage. 

**Expected behavior**
Quick load

**Attachments**
![GEknl2Hqh3](https://user-images.githubusercontent.com/60515654/80203922-3db04f00-8628-11ea-8217-1f5e86a5eb8b.gif)

**Specs (if applicable):**
 - Windows 10
- Maya PR114

**Comment by kxl-adsk** [comment]
@Xaia Can you measure in USD view and compare? The pure load of USD assets depends on USD library. When reporting performance issues like this one, please compare first.

**Comment by Xaia** [comment]
@kxl-adsk Well, it is embarrassing but I have not clue how to run usdview from MayaPR114 build.
I now that clarisse and houdini opens the file in 1 second but does not load any textures. Pretty sure this is what makes the scene load so long in Maya.

**Comment by santosd** [comment]
Hi @Xaia and @kxl-adsk, I took a look at this and found that loading in USD view and in Maya take the same amount of time about a minute for the Attic File for me. I think like you said Xaia this is related to textures. Maybe something we could look into speeding up.

**Comment by Xaia** [comment]
Pixar is already on to something. Not sure how this translates to Maya plugin though.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!searchin/usd-interest/nvidia$20attic%7Csort:date/usd-interest/8Ml3CTrwcsc/GJwup0wCAwAJ

**Comment by HdC-adsk** [comment]
Two notes for this issue:

* VP2RenderDelegate stills takes longer than HdSt when loading the scene (70s vs. 30s). The material networks are not exactly duplicate because of different node names, but it looks like most of them have the same node types and connections. I think we will need a further optimization in VP2RenderDeleagete to reuse the same shader for this type of similar material networks.
* The scene also has textures but I guess the texture loading performance will be most likely similar between VP2RenderDelegate and HdSt. I will profile and confirm after the above bottleneck is fixed.

**Comment by HdC-adsk** [comment]
Just to post my recent progress on this issue:

As I mentioned above VP2RenderDelegate originally took 70s to load the NV attic scene, which presented two major overheads:
* 54s on texture loading
* 16s on material realization

With https://github.com/Autodesk/maya-usd/pull/1043 the material realization overhead (16s) is gone, so it takes 54s now.

It is still slower than HdSt (30s). I was expecting VP2RenderDelegate texture loading performance could be equivalent to HdSt because we share the same code path to read images from disk, so we will need to understand the reason of the gap.
