### ISSUE TITLE
maya reference parenting error under a pxrUsdReferenceAssembly

### ISSUE THREAD

**Issue by agelosc** [Autodesk/maya-usd#535]
**Describe the bug**
Parenting a maya reference on a pxrUsdReferenceAssembly node issues the following error:
`// Error: line 1: Cannot add node '<referenced node>' to asset because it is in a different file. //`
referenced node is the name and namespace of the referenced object.
If the referenced object is grouped (has a local transform as a parent) then the group can be parented to the pxrAssembly with no error.

**Steps to reproduce**
1. Create a pxrUsdReferenceAssembly node. Doesn't make a difference if it has something loaded or not.
2. Add any maya reference to the scene.
3. Parent the referenced root node to the pxrUsdReferenceAssembly node.

**Expected behavior**
I'm trying to have a rig variant which is required to be a maya scene. I'm writting a custom SelectVariant method that loads and unloads a maya reference (since pxrUsdReferenceAssembly doesn't load a MayaReference type prim) and I would like to have it contained within the assebly node. Since parenting is generally permitted, I'm assuming parenting a referenced object directly on a pxrAssembly node should also work. I'm not possitive this is a bug or this behaviour is expected for some reason I don't understand. The error looks vague enough for it to be bug but please let me know if it's not.

**Specs (if applicable):**
 - Windows 10
 - Maya 2020
 - Maya USD v0.1.0
 - Pixar USD v20.02

**Comment by santosd** [comment]
Hi @agelosc I took a look at this and was able to replicate the issue in the pxr plugin.

**Comment by agelosc** [comment]
I transitioned to the al_usdmaya plugin as I understand that the pxr assembly will eventually be deprecated. Please feel free to close this issue, unless you want to investigate this for your own reasons. 

Thank you for having a look.

**Comment by mattyjams** [comment]
Hi @agelosc, looks like you've long since moved on from this, but just wanted to close the loop here.

Parenting other nodes underneath `pxrUsdReferenceAssembly` nodes is not really a supported workflow. We're expecting that everything beneath the assembly is a result of activating one of the assembly's representation, which will create nodes based on the contents of the USD stage in the assembly. Deactivating a representation or otherwise unloading the assembly will destroy everything below it.

As you noted, Maya's assembly framework is effectively deprecated now and we'd generally encourage anyone looking at `pxrUsdReferenceAssembly` to consider either the Autodesk proxy shape with UFE or Animal Logic's plugin instead. I think the latter should provide a pretty good fit for the workflow you're after, so glad to hear that you're on your way already.

Thanks! Closing this out...
