### ISSUE TITLE
[MAYA-105263]Draw performance of Maya's data model for very dense meshes is faster than native USD (VP2RenderDelegate or mtoh)

### ISSUE THREAD

**Issue by Xaia** [Autodesk/maya-usd#566]
I've been stress testing USD capabilities with 50 million polygon mesh and I encountered interesting behavior. 
Imported FBX file has higher frame rate than USD Stage. 
In my case it is USD VP2 **63FPS** USD MTOH  **21FPS** vs MTOH FBX **55FPS** vs VP2 FBX **77-80FPS**

MTOH has some problems with displaying the entire mesh. Don't think the mesh is corrupted, tested 

**Steps to reproduce**
1. Grab dense mesh
2. Turn on Frame counter

**Expected behavior**
Same or better performance

**Attachments**

USD VP2
![Lygg3NFpVu](https://user-images.githubusercontent.com/60515654/83810240-197c6f00-a6b8-11ea-9db6-30f4f4fe58c1.gif)

USD MTOH
![QRM3bcL0I4](https://user-images.githubusercontent.com/60515654/83811165-93612800-a6b9-11ea-925f-fd85907be846.gif)

MTOH FBX
![JNJcDECx6X](https://user-images.githubusercontent.com/60515654/83812049-20f14780-a6bb-11ea-810d-875e7c84f39d.gif)

VP2 FBX
![9wdeJmGj3F](https://user-images.githubusercontent.com/60515654/83812367-b42a7d00-a6bb-11ea-9dd2-01cc5dc431d3.gif)

**Specs (if applicable):**
- Windows 10
-  PR115

**Comment by kxl-adsk** [comment]
@Xaia can you share this asset with us?

**Comment by Xaia** [comment]
@kxl-adsk yes, here you go. The mesh is not final and there are some issues with the branches. After deleting them, frame count difference don't change though.
https://wetransfer.com/downloads/1b69893cc9cf63da8e666f208eda469820200605113727/34a041

**Comment by kxl-adsk** [comment]
Surprising...and yes, I was able to reproduce the issue. If you don't mind, I will tweak the title a bit since what we are comparing here is drawing of something that is in Maya (importing FBX is translating meshes into Maya data model) vs native draw performance of USD (with VP2RenderDelegate or Hydra Storm is using mtoh).

**Comment by Xaia** [comment]
No worries, glad I can help! Don't abuse the model too much ;)

**Comment by williamkrick** [comment]
I spent some time understanding this today with this workflow:

1. Import the fbx file into Maya, tumble and measure performance. I get around 150fps.
2. Export the file to USD.
3. In a new scene create a mayaUsdProxyShape and set the file to be the newly created USD file. I get around 50fps.

What I found was the shading done by USD is significantly different from the shading done by Maya. By default the USDExport code seems to export UVs and Color Per Vertex. When I disable these options and re-export the scene USD uses the simpler shader without CPV and I get around 150fps.

I think the problem is with USD Export. It is creating CPV buffers that are full of a constant color. Those additional buffers changes the shading model USD uses to draw the objects, and the CPV shading model is much slower.

Two issues we can improve here:

1. Asking USD Export to export color sets probably shouldn't create a CPV buffer filled with a single color.
2. CPV rendering being more than 2x slower than the default material seems excessive. I'll have to investigate more to understand why this is happening.

**Comment by HdC-adsk** [comment]
@Xaia Is the USD asset exported from a Maya asset?

**Comment by Xaia** [comment]
@HdC-adsk Yes, USD asset was exported from a Maya asset. Checked with Maya PR117 and frames are dropping from 60fps to 12fps.

**Comment by HdC-adsk** [comment]
@Xaia Thanks for quick reply. I see the issue as well, I asked the source of the data in order to better understand how to fix it.

**Comment by HdC-adsk** [comment]
@Xaia Could you refresh the share link of the asset and post it in https://github.com/PixarAnimationStudios/USD/issues/1300? (Sorry that my machine is down so I couldn't access the file either). Pixar team is working on a fix and would like to validate on this particular asset.

**Comment by Xaia** [comment]
hi @HdC-adsk sure thing. On it :)

**Comment by Xaia** [comment]
Hi guys, 
@HdC-adsk 
I was testing new PR119 where this issue was "fixed" but unfortunately I am getting different results. 
Maya 2020.2 and Maya USD 0.3.0 - 35 FPS
Maya PR119 and Maya USD 0.5.0 - 33 FPS
Maya PR119 Native - 45 FPS
https://imgur.com/a/Z6J8pvq (gifs inside)

**Comment by HdC-adsk** [comment]
Hi @Xaia ,

Thanks for reporting the issue. I think you mean Maya USD 0.4.0 when you said 0.5.0. What is the USD core version you used to compile? Can you share your hardware spec info (esp. GPU)?

Hi @santosg87 ,

Can you retest the issue with Maya PR119 and Maya USD 0.4.0? Thanks.

**Comment by Xaia** [comment]
> Hi @Xaia ,
> 
> Thanks for reporting the issue. I think you mean Maya USD 0.4.0 when you said 0.5.0. What is the USD core version you used to compile? Can you share your hardware spec info (esp. GPU)

Yes sorry, a typo, it's 0.4.0.
I used compiled version for maya pr119 so I am guessing it's still 20.08. 
I am running on ryzen 3950x 64gigs and 2x gtx 1070

**Comment by HdC-adsk** [comment]
Thanks. I cannot reproduce the issue. Both data models are running at 124fps on my RTX5000 card when tumbling the camera.

Let's wait to see if George can reproduce it.

**Comment by HdC-adsk** [comment]
@Xaia One possible reason I can guess is that the build/install structure of MayaUSD binaries has been changed in PR119 so you can probably still be using the previous 0.3.0 binaries? Can you confirm the version by clicking the "i" icon in the plug-in manager:

![image](https://user-images.githubusercontent.com/1897048/93817953-b3483780-fc27-11ea-8a41-42df4c7ceae5.png)

**Comment by HdC-adsk** [comment]
@Xaia One possible reason is that the build/install directory structure has been changed in PR119 so it could be that you are still using previous 0.3.0 binaries? Did you clean the previous binaries and build?

**Comment by Xaia** [comment]
Yes I did clean previous binaries and build. Looks like Maya is loading 0.4.0
![image](https://user-images.githubusercontent.com/60515654/93823322-ec050280-fc61-11ea-8e62-a6e5eb61296d.png)

I will reinstall and manually delete leftovers, maybe this is causing some issues. I noticed that I am getting less frames only on really dense mesh ~50M. Mesh around 15M triangles does not have that problem and its running 150FPS+.

**Comment by HdC-adsk** [comment]
Yes, the super-dense mesh might be different. The 15M triangle mesh is what I have to test. Could you share the 50M triangle mesh?

**Comment by Xaia** [comment]
Sure will do once I am back home from work. I am pretty sure you could use maya sphere subdivided 8 times though :)

**Comment by Xaia** [comment]
@HdC-adsk Here you go :) https://we.tl/t-onMUHp1EOU
Just checked with the ~50M Maya sphere and getting the same results. From 66FPS to 55FPS.
