### ISSUE TITLE
No restTransforms in USD file when exporting skeleton

### ISSUE THREAD

**Issue by stevkalinowski** [Autodesk/maya-usd#603]
**Describe the bug**
If we export a mesh skinned to a skeleton, and the skeleton is not animated, it seems the restTransforms is not stored in the USD file.  The problem is that when we import the USD file back into Maya all its joints are at the origin.

**Steps to reproduce**
1 Open shared Maya scene referenced below.
2 Run mel command to export "file -force -options ";exportSkels=auto;exportSkins=auto" -type "USD Export" -pr -ea "D:\\character_test.usd";"
3 File > New
4 File > Import, choose the usd file just saved.

**Expected behavior**
When exporting a USD file I would expect a skeleton to Import back in at the same pose.

**Attachments**
Uploaded "character_export.zip" to Activision sharepoint drive.

**Specs (if applicable):**
Windows 10
Maya PR115

**Comment by santosd** [comment]
Hi @stevkalinowski, I wasn't able to find the sharepoint, Wondering if it is possible to upload it here or if you could send me a link to the sharepoint.

**Comment by stevkalinowski** [comment]
Can you try this link:
https://share.autodesk.com/:u:/r/sites/ACME/Shared%20Documents/Accounts%20(External%20Share)/Activision%20(External%20Share)/Upload%20Area/From%20Stev/character_export.zip?csf=1&web=1&e=ofYQek

Stev

**Comment by santosd** [comment]
Hi @stevkalinowski, Thank you for responding the share takes me to a page to request permission however, I was able to find the file in an email from Will Telford. I am currently running through the steps and when I run the command to export, I am hitting a hard crash with this particular file. It seems on my end that it doesn't like the exportSkels option. If I remove that it no longer crashes. Once I import the file I am not seeing the issue but likely because the skeleton isn't in the file.  I've tried other files and am not getting crashes with those using the exportSkels option. I am going to log the crash as a defect and see if I can get a dev to take a look at it. Once the crash is fixed I can take a look at the other issue you are seeing.

**Comment by stevkalinowski** [comment]
cool, thanks for the update.

**Comment by nxkb** [comment]
@stevkalinowski one question for you, to see this is similar to what I saw before: Is the rest pose you're looking for in a SkelAnimation prim instead of the SkelRoot? If so was the skin bound to your skeleton in the same position as the "rest" pose?

**Comment by stevkalinowski** [comment]
I’m also posting a response from Koen.  We’re both having issues posting comments using the website, we can an error.


Hello all,
I work with the same data as Stev. If I remember correctly, the maya exporter would always export the mesh and the skeleton in the bind pose pose and then export a SkelAnimation to reflect the current pose ( when not exporting animation).
Instead of exporting and binding the SkelAnimation, when no exporting animation explicitly, we'd prefer the current pose to go into the rest pose attribute in the usdSkel:
"
The restTransforms property of a Skeleton provides local space rest transforms of each joint, which serve as a fallback values for joints that have not been overridden by an animation. As with bindTransforms, the restTransforms are ordered according to the order of the joints attribute.
The restTransforms may be considered optional, but if left unspecified, the Skeleton must be bound to a complete, non-sparse animation. It is common for the restTransforms to be refer to the same pose as the bindTransforms, only in joint-local space, rather than world space, but this is not requried.
"
( from https://graphics.pixar.com/usd/docs/api/_usd_skel__schema_overview.html#UsdSkel_SchemaOverview_SkelRoot)
We actualy went a step further, as we dont store the bind pose in our models, we store the pose at the frame the user chooses. We export both the mesh and the skeleton in this pose. We found that if we store the mesh in the bind pose, we ended up relying on the usd skinning deformations to get back to the desired pose and as this is just linear blend skinning, it often does not match what we would see in maya.
So we currently export the deformed mesh, the skeleton in the pose as seen on screen and then the rest-transforms to match those. This way we dont need to bind any animations to get the right pose.
Hope that all makes sense.
Koen

**Comment by santosd** [comment]
I have been able to run some further tests on this file and on my end in the latest Maya\MayaUSD PR129 beta release and for me the joints are exporting and importing in the same place. However, it seems that some of the skinning is broken. Let me know if you would like me to and if it would be okay for me to share screen shots of what I am seeing in the scene, in this public discussion.

**Comment by santosd** [comment]
Hi @stevkalinowski, It is possible that the skinning issue is a separate thing and we can log that as a different issue. To confirm though, in regards to the joints export\import. In the screen recording I emailed you it seems to me that the joints are coming in at the same location as they were exported from can you verify that? It is possible that this used to be an issue, but has since been resolved or maybe I am missing a step and therefore am not seeing the issue.

**Comment by stevkalinowski** [comment]
yeah, strictly speaking of the joints, they do come in at the correct positions.

**Comment by wtelford** [comment]
Sounds like the joints are exporting as intended and the remaining issue is logged in #1821
