### ISSUE TITLE
usdqt?

### ISSUE THREAD

**Issue by suekieza** [Autodesk/maya-usd#67]
Hey there,

Is usdqt part of the build? I built the master and it doesn't seem to have it, is this correct?

I'm trying to build the Refractoring_Sandbox but alas I am running into build issues again.
[build_log.txt](https://github.com/Autodesk/maya-usd/files/3762446/build_log.txt)
[CMakeError.log](https://github.com/Autodesk/maya-usd/files/3762447/CMakeError.log)

 

Thanks Sue

**Comment by HamedSabri-adsk** [comment]
@suekieza Luma's usdqt are not used in the project.

**Comment by HamedSabri-adsk** [comment]
> I'm trying to build the Refractoring_Sandbox but alas I am running into build issues again.

By looking at your log, I can see that you are building against a wrong version of USD.

Please have a look at DEVELOPER.md here to make sure you use the correct version:

https://github.com/Autodesk/maya-usd/blob/refactoring_sandbox/doc/DEVELOPER.md

**Comment by suekieza** [comment]
Thanks will build with the right versions. Bit confused about the luma pictures thing, is it only hydra that's coming from them then?

Thanks for the help by the way :D/

**Comment by suekieza** [comment]
Hey Hamed, Still no luck. Updated to latest USD, am I missing something else?
[CMakeError.log](https://github.com/Autodesk/maya-usd/files/3767001/CMakeError.log)
[build_log.txt](https://github.com/Autodesk/maya-usd/files/3767003/build_log.txt)

Thanks

**Comment by BigRoy** [comment]
> Updated to latest USD, am I missing something else?

You shouldn't be using the *latest* but instead you should be using the [exact commit as referenced in `DEVELOPERS.md`](https://github.com/Autodesk/maya-usd/blob/refactoring_sandbox/doc/DEVELOPER.md) for that specific branch. Even though it says `>19.07` currently for me it didn't work with the latest, but when I used the specific commit then it worked. I'm not sure from your build logs it is the same issue, but it could be worth investigating whether you have that exact USD commit checked out and build.

However since your `CMakeError.log` states errors about `pthread_create exists` it sounds like it could also be related to this issue: https://github.com/Autodesk/maya-usd/issues/62

**Comment by suekieza** [comment]
It gives that error regardless of what is wrong(Hans suggests https://groups.google.com/forum/#!searchin/usd-interest/sandbox%7Csort:date/usd-interest/SQ2BDnreo6s/VZfEMN1mAQAJ). 
The master branch builds fine for me. Was just trying the sandbox, but I don't think the sandbox will have what I want either(AL interface/UI as demo'd in https://vimeo.com/365638295). I thought that there was some sort of interface/UI that builds with this Maya plugin. But now I'm not sure there is. 
I was thinking along the lines of Solaris in Houdini. The Plugin as is, is super limited and doesn't seem to export correctly(Tried to export mesh and view it in usdview) but it didnt work. Houdini mesh(export as usd) displays just fine in both maya and usdview.

**Comment by BigRoy** [comment]
I know this issue is closed, but just to reference where you can currently find these interfaces I'm commenting here.

@suekieza The particular UI your a looking for might be the one from [`Lumapictures/usd-qt`](https://github.com/LumaPictures/usd-qt) and then particularly the `outliner` editor in `pxr.usdQtEditors.outliner` (which is part of `usd-qt` but merges into the `pxr` python namespace).

Here's an example of what it looks like (note that I applied a custom stylesheet to this):
![usd_qt_outliner](https://user-images.githubusercontent.com/2439881/68036581-47cf4180-fcc6-11e9-880c-28c025c7b97c.png)

However, the tool itself does not automatically connect to any of the AL proxy shapes and I don't believe that editor code that Animal Logic showcases in this video is publicly available anywhere. Nevertheless the features in the `LumaPictures/usd-qt` `outliner` are the perfect basis to build it. Note for example how [similar it looks the older implementation to this demo by Animal Logic (see left hand side)](https://www.youtube.com/watch?v=DaxLk6pHijw&feature=youtu.be&t=195)

Also be aware that the interface doesn't automatically manage the `usdProxy` shape in the Maya scene. That connection would also have to be set up manually, but as `maya-usd` matures it would make sense to see code for that becoming available too.
