### ISSUE TITLE
python import error mayaUsd_createStageWithNewLayer

### ISSUE THREAD

**Issue by mreinhardmikros** [Autodesk/maya-usd#931]
Hello,
I am getting python import errors for the two entries in the Edit->Scene Management->USD menu, for example of
mayaUsd_createStageWithNewLayer. This is with a custom build of maya-usd.
Looking at the mod template I think that the folder where these ptython files live in (plugin/adsk/scripts) is never added to the PYTHONPATH.
If I extend line 16 of the mod file to
PYTHONPATH+:=lib/python:scripts
the commands are available.
Cheers,
Marcel

**Specs (if applicable):**
 - CentOs 7.6
 - gcc 6.3.1
 - Maya 2019
 - Maya USD tag 0.5.0
 - Pixar USD tag 20.11

**Comment by mreinhardmikros** [comment]
> Edit
Correct menu is
Create->Scene Management->USD

**Comment by seando-adsk** [comment]
It should be getting added to the PYTHONPATH automatically because we define MayaUsd to be a plugin in the mod file here: https://github.com/Autodesk/maya-usd/blob/dev/modules/mayaUSD.mod.template#L23

What happens is that Maya will automatically look for a folder named **scripts** under the relative path from that line - in this case `${CMAKE_INSTALL_PREFIX}/plugin/adsk` and add that path to both the `PYTHONPATH` and `MAYA_SCRIPT_PATH`.

Without your change can you attach your mayaUsd.mod file and the output from:
`getenv "PYTHONPATH";`
`getenv "MAYA_SCRIPT_PATH";`

**Comment by mreinhardmikros** [comment]
You are righ

**Comment by mreinhardmikros** [comment]
You were absolutely right, this was a problem in my own config. Sorry for the noise!
